cpu:
	gcc cpu_accelerometer.c -o cpu_accelerometer


gpu:
	nvcc gpu_accelerometer.cu -o gpu_accelerometer

accel:
	gcc accelerometer.c -o accelerometer

clean:
	rm -f cpu_accelerometer gpu_accelerometer accelerometer
